### PR TITLE
Avoid importing the whole lodash

### PR DESCRIPTION
**Pull request by ratson**

### CODE REVIEW

**Comment by rt2zz** [comment]
Do you know why redux does not use babel-lodash? I based my implementation on that.

**Comment by ratson** [comment]
Because the author avoided `import _ from 'lodash`, by importing used functions directly, e.g. `import isPlainObject from 'lodash/isPlainObject'`

**Comment by rt2zz** [comment]
:+1:

**Comment by jorilallo** [comment]
Thanks for making the change, it has a pretty significant effect on the bundle size. Would be nice to get a release as `lib` isn't part of the repo.

**Pull request merged**
