### PR TITLE
Add correct PersistGate defaultProps to support newer flow versions 

### PR DESCRIPTION
**Pull request by erksch**
As mentioned in #953 there are type errors with some flow versions in the PersistGate component.

The problem with flow is described here:
https://github.com/facebook/flow/issues/1660

A possible solution is described [later in the issue](https://github.com/facebook/flow/issues/1660#issuecomment-386619834) and was already proposed by the creator of issue #953.

So what I did is adding `children: null` to the defaultProps and making `loading and children` not optional anymore.

### CODE REVIEW

**Comment by kareemsalah227** [comment]
I only have a quick comment, correct me if I'm wrong please.

You can provide a loading component or you can ignore it, so it's kind of "optional", I think this might be the reason it was set optional in the flow type? If that is the case, is there another solution to make it optional and get rid of the flow error? (maybe by providing a default value or something).

Please let me know what do you think.

**Comment by erksch** [comment]
Removing the `?` is okay here because flow will mark them as optional automatically when defaultProps are defined. You can read about it here: https://github.com/facebook/flow/issues/1660#issuecomment-386619834

**Comment by erksch** [comment]
And there seems to be no other option than removing the optional flag :/

**Comment by kareemsalah227** [comment]
Actually there is, I'll create a quick PR for that...

**Comment by kareemsalah227** [comment]
Ops, looks like I don't have permissions to push a branch to the repo, what should I do? @erksch

**Comment by kareemsalah227** [comment]
Nevermind, I've never contributed to an open source repo before, pardon my ignorance.
I forked the repo and created a cross-repo PR.
https://github.com/rt2zz/redux-persist/pull/975

There's a decent description in there, let me know what do you think @erksch .

**Pull request merged**
