### PR TITLE
Add types directory to package.json

### PR DESCRIPTION
**Pull request by Ailrun**
@avendiart

### CODE REVIEW

**Comment by avendiart** [comment]
Nice, that should do the trick :)

**Comment by Deadarius** [comment]
Please, desperately need this in

**Comment by Ailrun** [comment]
@rt2zz Could you review/merge this?

**Comment by aguynamedben** [comment]
I've been trying to help this project, which needs a lot of help if anybody is interested. I can merge this, doing now. I don't have the power to cut a new release, but you can link your package.json to the right sha1 hash.

**Pull request merged**
