### PR TITLE
Attempt to fix Persistor creation flow error

### PR DESCRIPTION
**Pull request by Baransu**
Attempt to fix: #685 
Potentially fixes: #690 
Would be great to hear some feedback about this change 😃

### CODE REVIEW

**Comment by rt2zz** [comment]
I like this change, but if I am not mistaken register and rehydrate will be broken in this case as they both depend on the store. I will try to take a look today.

**Comment by Baransu** [comment]
Tests seems to work find and in my basic setup its working. I’ll be glad if you could look into it :)

**Comment by rt2zz** [comment]
ah ok I had to read up on hoisting to understand how this works 👍

**Comment by rt2zz** [comment]
note: I reworked it a bit to not rely on hoisting - perf should be identical but this seems like a more conservative setup:  https://github.com/rt2zz/redux-persist/commit/c090a323edaca664fce1137351e795ba4183341c

Also updated IntervalId to any for now for backwards flow compat

**Pull request merged**
