### PR TITLE
Return Promise from purge() in persistStore.js

### LINKED ISSUE #254: purge() in persistStorage.js should return a promise
Hi, I noticed that the `purge()` function in [persistStorage.js](https://github.com/rt2zz/redux-persist/blob/master/src/persistStore.js) doesn't return the promise that the `persistor.purge()` returns. 

I'll open a PR with a fix.

### PR DESCRIPTION
**Pull request by domlazic**
Fixes #254

### CODE REVIEW

**Comment by rt2zz** [comment]
ty

**Comment by domlazic** [comment]
np, glad to help. Do you maybe have an idea when will you update the npm package to include this change? thanks!

**Comment by rt2zz** [comment]
done https://github.com/rt2zz/redux-persist/commit/676e68b930057f62cb4e7501ae3d764386a41928

**Comment by SleeplessByte** [comment]
@rt2zz cc @domlazic type definitions are not updated to reflect this change.

**Comment by rt2zz** [comment]
@SleeplessByte indeed good catch. PR greatly appreciated!

**Pull request merged**
