### PR TITLE
Update redux in devDependencies & Fix typescript typings

### LINKED ISSUE #700: typescript incompatible with latest version of redux-persist
**Versions:**
TS: 2.7.1
redux-persist: 5.6.5

All of the sub directory imports are not possible when using typescript with redux-persist.
Example:
```javascript
import storage from 'redux-persist/lib/storage'
// error:
[ts]
Could not find a declaration file for module 'redux-persist/lib/storage'. '.../node_modules/redux-persist/lib/storage/index.js' implicitly has an 'any' type.
  Try `npm install @types/redux-persist` if it exists or add a new declaration (.d.ts) file containing `declare module 'redux-persist';`
```

### LINKED ISSUE #833: Make dependency on react optional
I currently use redux-persist 4.9.1 in an **Angular** 6 application with angular-cli and **angular-redux/store** and redux 4.0.0. It is a typescript 2.7 application.
When I upgrade to redux-persist 5.9.1 there is the following error:

```
 92% after chunk asset optimization SourceMapDevToolPlugin main.js generate SourceMapERROR in node_modules/redux-persist/src/index.d.ts(69,46): error TS2307: Cannot find module 'react'.
node_modules/redux-persist/src/index.d.ts(91,38): error TS2304: Cannot find name 'React'.
```
It would be good if the integration with **react** would be **optional**.

### LINKED ISSUE #875: Updates to store aren't being persisted. V5
I am trying to persist two pieces of the store.  One being auth info and the other being user preferences.

`const initialState = { auth: {}, preferences: defaultUserPreferences };`
When the use logs in, auth is updated and persists.  Later, I ask the user for push notification permissions and then I want to update `auth.push_token: null` to contain the push_token.  The problem is that it doesn't persist.

Also, I set default user preferences for each user which is fine, but as the user updates preferences, the new preferences aren't persisted.

```
// configureStore.js

import { createStore, applyMiddleware } from 'redux';
import { persistStore, persistReducer } from 'redux-persist';
import storage from 'redux-persist/lib/storage';
import logger from 'redux-logger';
import axios from 'axios';
import axiosMiddleware from 'redux-axios-middleware';

import { ENDPOINT } from 'react-native-dotenv';
import reducer from '../reducer';

const persistConfig = {
  key: 'root',
  storage,
  whitelist: ['auth', 'preferences'],
};

const client = axios.create({
  baseURL: ENDPOINT,
  responseType: 'json'
});

const persistedReducer = persistReducer(persistConfig, reducer);

export default () => {
  const store = createStore(persistedReducer, applyMiddleware(axiosMiddleware(client), logger));
  const persistor = persistStore(store);
  return { store, persistor };
}
```

```
// App.js
import React from 'react';
import { ActivityIndicator, AsyncStorage } from 'react-native';
import { Provider } from 'react-redux';
import { PersistGate } from 'redux-persist/integration/react';

import Navigator from './Navigator';
import configureStore from './store/configureStore';

const { persistor, store } = configureStore();

export default class App extends React.Component {
  render() {
    return(
      <Provider store={store}>
        <PersistGate loading={<ActivityIndicator />} persistor={persistor}>
          <Navigator />
        </PersistGate>
      </Provider>
    );
  }
}
```

```
// reducer.js
export const SET_AUTH = 'app/auth/SET_AUTH';
export const UPDATE_AUTH = 'app/auth/UPDATE_AUTH';
export const UPDATE_AUTH_SUCCESS = 'app/auth/UPDATE_AUTH_SUCCESS';
export const SET_PREFERENCES_SUCCESS = 'app/preferences/SET_PREFERENCES_SUCCESS';

import { defaultUserPreferences } from './helpers/defaultUserPreferences';

const initialState = { auth: {}, preferences: defaultUserPreferences, pets: [] };

export default function reducer(state = initialState, action) {
  switch (action.type) {
    case SET_AUTH:
      return { ...state, loading: false, auth: action.payload.data };
    case UPDATE_AUTH:
      return { ...state, loading: true };
    case UPDATE_AUTH_SUCCESS:
      return { ...state, loading: false, auth: action.payload.data.user[0] };
    case SET_PREFERENCES_SUCCESS:
      return { ...state, loading: false, preferences: action.payload.data };
    case "persist/PERSIST":
      console.log('------------------------PERSIST HAS BEEN CALLED------------------------')
    default:
      return state;
  }
}

export function setAuth(data) {
  return {
    type: SET_AUTH,
    payload: { data }
  };
}

export function updateAuth(user_id) {
  return {
    type: UPDATE_AUTH,
    payload: {
      request: {
        url: `/users/${user_id}`
      }
    }
  }
}

export function setPreferences(data) {
  return {
    type: SET_PREFERENCES,
    payload: { data }
  }
}
```

My main confusion is why auth is persisting initially but if it's updated and there is a hard refresh, I lose the updates.

### LINKED ISSUE #908: Reducer type incompatible with Redux (4.x) Reducer type
The `Reducer` type used in `persistCombineReducers` is defined as:
```js
type Reducer = (state: Object, action: Object) => Object
```
Whereas the `Reducer` type used in Redux is defined as:
```js
type Reducer<S, A> = (state: S | void, action: A) => S;
```
Hence, this flow error pops up when attempting to call `createStore`:
> Cannot call `createStore` because:
> - Either object type [1] is incompatible with undefined [2] in the first argument.
> - Or object type [1] is incompatible with undefined [2] in the first argument.

This seems like an incompatibility, or I might be doing things wrong...
Here is my setup:
```js
// root_reducer.js
/* @flow */

import { persistCombineReducers } from "redux-persist";
import { AsyncStorage } from "react-native";

import thing from "reducers/thing_reducer";

const config = {
  key: "root",
  storage: AsyncStorage,
};

const rootReducer = persistCombineReducers(config, { thing });

export default rootReducer;
```

```js
// store.js
/* @flow */

import { createStore, applyMiddleware, compose } from "redux";
import { persistStore } from "redux-persist";
import thunk from "redux-thunk";

import rootReducer from "reducers/root_reducer";

import type { Store } from "models/store";

const middleware = [thunk];
const composeEnhancers = window.__REDUX_DEVTOOLS_EXTENSION_COMPOSE__ || compose;

export const store: Store = createStore(
  rootReducer,
  composeEnhancers(applyMiddleware(...middleware))
);
export const persistor = persistStore(store);
```

```json
"dependencies": {
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-navigation": "^2.11.2",
    "react-navigation-redux-helpers": "^2.0.5",
    "react-redux": "^5.0.7",
    "redux": "^4.0.0",
    "redux-persist": "^5.10.0",
    "redux-thunk": "^2.3.0"
  }
```

### PR DESCRIPTION
**Pull request by Ailrun**
Resolves #908.
Resolves #875.
Resolves #833.
Resolves #700.
Resolves (Maybe?) #646.

1. Add TS typing test using `dtslint` (though there are only few tests...)
2. Extract typings into separate directory
3. Extract react integration typing into separate directory
4. Fix ill-typed actions, options, ...

### CODE REVIEW

**Comment by Ailrun** [comment]
@rt2zz Any opinion??

**Comment by rt2zz** [comment]
This looks great. Thanks Ailrun. 

I am going to take this in, any other typescript users please weigh in if you have any concerns.

**Comment by rt2zz** [comment]
perhaps we should rewrite things in typescript 🤔

**Comment by rt2zz** [comment]
gonna go with this in a prerelease, I have a ts project I can try this out in as well

**Comment by rt2zz** [comment]
available in redux-persist@5.11.0-alpha via `npm i --save redux-persist@next`

**Comment by avendiart** [comment]
Please add the `types` directory to the `files` property in `package.json` as the type definitions are not being included in the distributed package anymore.

**Comment by tnagorra** [comment]
Looks like `types` directory has been added in https://github.com/rt2zz/redux-persist/commit/8d58d1ee7759d1c7209705c0b342ae20f2954f3e, but it's not included in the latest release. :crying_cat_face:

**Comment by gausie** [comment]
@rt2zz this is still an issue sadly

**Comment by burtek** [comment]
> @rt2zz this is still an issue sadly

it is. @rt2zz any chance for releasing that?

**Comment by rt2zz** [comment]
this is pretty old, but the types in v6 have been updated. @burtek 	can you try `redux-persist@next` and see if that resolves the issues?

**Comment by rt2zz** [comment]
this is pretty old, but the types in v6 have been updated. @burtek 	can you try `redux-persist@next` and see if that resolves the issues?

**Comment by burtek** [comment]
@rt2zz I could, but I'm not allowed to use unstable versions in our product as per company's policy.

**Comment by gausie** [comment]
@burtek I think the idea is that you try it with that to confirm that it solves the problems

**Pull request merged**
