### PR TITLE
Added note on the important ordering of transforms

### PR DESCRIPTION
**Pull request by swernerx**
This part was pretty time consuming for me a probably other users.

### CODE REVIEW

**Comment by rt2zz** [comment]
thank you for looking into this and the PR! However I am actually quite suprised, I would expect the required order to be `transforms: [ immutableTransform(), createCompressor() ]` since we [reduce left](https://github.com/rt2zz/redux-persist/blob/master/src/createPersistor.js#L57) the transforms and it would not make sense to run transit-immutable on top of something the is already a string (the output of createCompressor).

I have a suspicion that there is actually a bug in redux-persist-trasnform-compress which is causing this. I will have to follow up tomorrow.

**Comment by rt2zz** [comment]
just published bugfix where compress was inconsistently applying serialization. Perhaps this fixes the issue for you?

**Comment by swernerx** [comment]
What exactly should I test now? Putting immutable before compressor?

**Comment by rt2zz** [comment]
yes. since the transforms apply left to right when storing state, it would be best to first immutable and then compress. In the other order I would not expect immutable to work, although please correct me if I am wrong.

**Comment by swernerx** [comment]
Seems to work now correctly. Thanks.

Usage:

```js
      persistStore(this.props.store, {
        storage: localforage,

        // Order is important. Immutable has to be the first!
        transforms: [
          immutableTransform(),
          createCompressor()
        ],
        blacklist: [
          "apollo"
        ]
      }
```

**Comment by rt2zz** [comment]
👍 thanks for bearing with and reporting!

**Pull request closed without merging**
