### PR TITLE
(types) Extending type definitions to all modules in redux-persist

### PR DESCRIPTION
**Pull request by rodrigoelp**
Created the type definition for every function, interface and instance.

### CODE REVIEW

**Comment by rodrigoelp** [comment]
Hi guys, In this pull request you will find a single file with all the type definitions segregated by modules. I still haven't pulled things on separate files as I had issues doing that (and the default exports for local storage, session and native storage gave me issues as well, I have not tested any of these yet)

I have not tested every declaration as I do not have an example for migration or state reconcilers.

It does not have any breaking in comparison to the previous commit.

**Comment by rt2zz** [comment]
awesome! thank you!

**Comment by rodrigoelp** [comment]
No worries :) glad I've been useful :)

**Comment by rodrigoelp** [comment]
By the way, should we update `Readme.md` file to remove the comment `Additionally v5 does not yet have typescript bindings.`?

**Comment by rt2zz** [comment]
done

**Comment by rodrigoelp** [comment]
Great, you are quick ;)

**Pull request merged**
