### PR TITLE
To avoid race conditions after `persistor.pause()` is called.

### PR DESCRIPTION
**Pull request by Morriz**
While keeping the atomicity of the storage operation intact.

### CODE REVIEW

**Comment by Morriz** [comment]
This will fix #452

**Comment by rt2zz** [comment]
the goal here is to prevent further save operations after pause is called?

**Comment by rt2zz** [comment]
nm just saw the issue, responding there.

**Comment by rt2zz** [comment]
as noted this will need to be rethought for v5, but for v4 👍

**Pull request merged**
